import type { LanDhcpConfig, SecurityConfig, WifiNetworks } from './types';

export const initialLanDhcpConfig: LanDhcpConfig = {
  lanIpInterface: '192.168.1.1',
  lanIpNetmask: '255.255.255.0',
  dhcpServerActive: 'Sim',
  dhcpIpPoolMin: '192.168.1.100',
  dhcpIpPoolMax: '192.168.1.200',
  dhcpSubnetMask: '255.255.255.0',
  dhcpGateway: '192.168.1.1',
  dhcpDnsServers: '8.8.8.8, 8.8.4.4',
};

export const initialWifiNetworks: WifiNetworks = {
  wlan1: {
    name: 'Wireless LAN 1',
    band: '2.4G',
    ssid: 'RJChronos_2G',
    password: 'password123',
    authMode: 'WPA2-PSK',
    status: 'Ativo',
    enabled: true,
    rfBand: '2.4GHz',
    standard: '802.11n',
    radioEnabled: true,
    totalAssociations: 3,
    ssidAdvertisement: true,
    wpaEncryption: 'AES',
    channelWidth: '20MHz',
    autoChannel: true,
    channel: 6,
    countryDomain: 'BR',
    txPower: '100%',
  },
  wlan2: {
    name: 'Wireless LAN 2',
    band: '2.4G',
    ssid: 'RJChronos_Guest_2G',
    password: 'guest2024',
    authMode: 'WPA2-PSK',
    status: 'Inativo',
    enabled: false,
    rfBand: '2.4GHz',
    standard: '802.11n',
    radioEnabled: false,
    totalAssociations: 0,
    ssidAdvertisement: false,
    wpaEncryption: 'AES',
    channelWidth: '20MHz',
    autoChannel: true,
    channel: 11,
    countryDomain: 'BR',
    txPower: '100%',
  },
  wlan3: {
    name: 'Wireless LAN 3',
    band: '5G',
    ssid: 'RJChronos_5G',
    password: 'password123',
    authMode: 'WPA3-PSK',
    status: 'Ativo',
    enabled: true,
    rfBand: '5GHz',
    standard: '802.11ac',
    radioEnabled: true,
    totalAssociations: 2,
    ssidAdvertisement: true,
    wpaEncryption: 'AES',
    channelWidth: '80MHz',
    autoChannel: true,
    channel: 36,
    countryDomain: 'BR',
    txPower: '100%',
  },
  wlan4: {
    name: 'Wireless LAN 4',
    band: '5G',
    ssid: 'RJChronos_Guest_5G',
    password: 'guest2024',
    authMode: 'WPA2-PSK',
    status: 'Inativo',
    enabled: false,
    rfBand: '5GHz',
    standard: '802.11ac',
    radioEnabled: false,
    totalAssociations: 0,
    ssidAdvertisement: false,
    wpaEncryption: 'AES',
    channelWidth: '40MHz',
    autoChannel: false,
    channel: 149,
    countryDomain: 'BR',
    txPower: '75%',
  },
};

export const initialSecurityConfig: SecurityConfig = {
  tpAccessFromWan: 'Disabled',
  ftpAccessFromLan: 'Enabled',
  userInterfaceAccessFromWan: 'Disabled',
  userInterfaceAccessFromLan: 'Enabled',
  sshAccessFromWan: 'Disabled',
  sshAccessFromLan: 'Enabled',
  sambaAccessFromWan: 'Disabled',
  sambaAccessFromLan: 'Enabled',
  telnetAccessFromWan: 'Disabled',
  telnetAccessFromLan: 'Disabled',
  wanIcmpEchoReply: 'Block',
  sshService: 'Enabled',
  telnetService: 'Disabled',
  cliUsername: 'admin',
  cliPassword: 'admin123',
  webUserAccount: 'Enabled',
  webUserName: 'user',
  webUserPassword: 'user123',
  webAdminAccount: 'Enabled',
  webAdminName: 'admin',
  webAdminPassword: 'admin456',
};
